seed: 7
device: cpu

environment:
  id: InvertedPendulum-v5
  render_mode: human
  episodes: 1
  max_episode_steps: 1000

model:
  simulation_timestep: 0.02
  frame_skip: 2
  min_action: -3.0
  max_action: 3.0
  healthy_angle_limit: 0.2
  cart_position_limit: 1.0
  rollout_threads: 4

cost:
  pole_angle_weight: 5.0
  pole_angular_velocity_weight: 1.0
  cart_position_weight: 3.7
  cart_velocity_weight: 1.9
  action_weight: 0.24

  pole_angle_scale: 0.2
  pole_angular_velocity_scale: 2.0
  cart_position_scale: 1.0
  cart_velocity_scale: 2.0
  action_scale: 3.0

  failure_penalty: 100.0
  terminal_weight: 10.0

mppi:
  horizon: 15
  num_samples: 380
  temperature: 3.0
  noise_sigma: 0.15
  num_iterations: 1
  sampling_correction: true
